version: 2
updates:
  - package-ecosystem: npm
    directory: /snippy/backend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /snippy/frontend
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /snippy/backend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /snippy/frontend
    schedule:
      interval: weekly
